services:
  - type: web
    name: jace-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dportfolio.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: PYTHON_VERSION
        value: 3.11
    plan: free